env_name: hopper-medium-expert-v2
output_file: dataset/hopper-medium-expert-v2-risky.hdf5
wrapper:
  type: pose
  prob_pose_penal: 0.1
  cost_pose: -50.0
  healthy_angle_range: [-0.17, 0.04]
  done_if_exceed_factor: 100.0
